---
- name: "setup tomcat"
  hosts: all
  become: true
  tasks:
# Install Java
    - name: "Install Java on RedHat"
      when: ansible_os_family == 'RedHat'
      yum:
        name: java
        state: installed

    - name: "Install Java Ubuntu"
      when: ansible_os_family == 'Debian'
      apt:
        name: default-jdk
        state: present

# Download tomcat package
    - name: "Download Tomcat"
      get_url: # used for wget; search google: wget command in ansible
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.84/bin/apache-tomcat-8.5.84.tar.gz 
        dest: /opt

# Untar .tar.gz
    - name: "Extract tomcat"
      unarchive: # search google: unzip command in ansible
        src: /opt/apache-tomcat-8.5.84.tar.gz
        dest: /opt
        remote_src: yes # This tells ansible to perform the task on remote-machine and not on local machine

# Give Execution permission on startup.sh
    - name: "Give Execution Permission to startup.sh"
      file: # Search google: file permissions command in ansible
        path: /opt/apache-tomcat-8.5.84/bin/startup.sh
        mode: ugo+x

# Start the Services
    - name: "Start tomcat services"
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.84/bin


