---
- hosts: all
  become: true
  vars:
    user: john # 'user' is a varibale-name
  tasks:
    - name: Create User
      user: 
        name: "{{ user }}" # referening variable: user
        shell: /bin/bash