---
# handlers file for setup-apache
- name: "Start httpd service"
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"

- name: "restart apache"
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: "Start apache2 service"
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"

- name: "restart apache2"
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"
