--- 
- name: This playbook will uninstall httpd Package
  hosts: rhel # since yum doesn't work on ubuntu machines
  become: true
  tasks:
    - name: "Stopping httpd service"
      service:
        name: httpd
        state: stopped

    - name: "UnInstalling APACHE HTTPD"
      yum:
        name: httpd
        state: removed