---
- name: This playbook creates a file or directory
  hosts: all
  become: true
  tasks:
    - name: "Create file: "
      file:
        path: /home/ansadmin/demofile.txt
        state: touch # for directory use 'directory'